routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserDashboardController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middlware' => 'auth'], function() {

    Route::group(['prefix' => 'dashboard'], function() {
        Route::get('/admin', [AdminDashboardController::class, 'index'])->middleware('role.admin')->name('dashboard.admin');
        Route::get('/user', [UserDashboardController::class, 'index'])->name('dashboard.user');
    });

    Route::resource('categories', '\App\Http\Controllers\CategoryController')->middleware('role.admin')->except(['show']);

    Route::resource('{category_id}/products', '\App\Http\Controllers\ProductController')->middleware('role.admin')
        ->except(['index', 'edit', 'update', 'show', 'delete']);
});

resources/views/dashboard/admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" style="display: flex;justify-content: space-between">
                    {{ __('Categories') }}

                    <div class="">
                        <a href="{{ route('categories.create') }}" class="btn btn-success">Create</a>
                    </div>
                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif

                    <div class="row">
                        <div class="col-md-12">
                            <ul>
                                @forelse ($treeWiseCategories as $categoryArr)
                                    @include('categories.partials.tree-view', compact('treeWiseCategories'))
                                @empty
                                    <li>No records found..</li>
                                @endforelse
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/user.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('User Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection