routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserDashboardController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middlware' => 'auth'], function() {

    Route::group(['prefix' => 'dashboard'], function() {
        Route::get('/admin', [AdminDashboardController::class, 'index'])->middleware('role.admin')->name('dashboard.admin');
        Route::get('/user', [UserDashboardController::class, 'index'])->name('dashboard.user');
    });

    Route::resource('categories', '\App\Http\Controllers\CategoryController')->middleware('role.admin')->except(['show']);

    Route::resource('{category_id}/products', '\App\Http\Controllers\ProductController')->middleware('role.admin')
        ->except(['index', 'edit', 'update', 'show', 'delete']);
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $guarded = [];

    public function rules()
    {
        return [
            'title' => 'string|max:255|unique:categories,title,' . $this->id,
            'parent_id' => 'nullable|exists:categories,id'
        ];
    }

    public function parent()
    {
        if ($this->hasParent()) {
            return $this->belongsTo(self::class);
        }

        return null;
    }

    public function hasParent()
    {
        if ($this->parent_id) {
            return true;
        }

        return false;
    }

    public function scopeParentId($query, $parentId)
    {
        return $query->where('parent_id', $parentId);
    }

    public function getParentTitle()
    {
        if ($this->hasParent()) {
            return $this->parent->title;
        }

        return null;
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function hasProducts()
    {
        return $this->products()->count() ? true : false;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('title')->paginate(20);

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = Validator::validate(request()->all(), (new Category)->rules());

        $category = Category::create($data);

        if ($category) {
            $request->session()->flash('success-message', 'Category added successfully!');
        } else {
            $request->session()->flash('error-message', 'Error occurred!');
        }

        return redirect()->route('dashboard.admin');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $data = Validator::validate(request()->all(), $category->rules());

        $category = $category->update($data);

        if ($category) {
            $request->session()->flash('success-message', 'Category updated successfully!');
        } else {
            $request->session()->flash('error-message', 'Error occurred!');
        }

        return redirect()->route('dashboard.admin');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $result = $category->delete();

        if ($result) {
            session()->flash('success-message', 'Category deleted successfully!');
        } else {
            session()->flash('error-message', 'Error occurred!');
        }

        return redirect()->route('dashboard.admin');
    }
}

resources/views/categories/partials/tree-view.blade.php
<li class="mt-3">
    <span class="mr-5">
        {{ $categoryArr['category']->title }}
    </span>
    <span>
        <a href="{{ route('products.create', [$categoryArr['category']->id]) }}" class="btn btn-primary btn-sm">Add Product</a>

        <a href="{{ route('categories.edit', $categoryArr['category']) }}" class="btn btn-warning btn-sm">Edit</a>

        <a class="btn btn-danger btn-sm" href="{{ route('categories.destroy', $categoryArr['category']) }}" onclick="event.preventDefault();
                                                                document.getElementById('delete-form').submit();">
            {{ __('Delete') }}
        </a>

        <form id="delete-form" action="{{ route('categories.destroy', $categoryArr['category']) }}" method="POST" class="d-none">
            @csrf
            @method('DELETE')
        </form>

        @if ($categoryArr['category']->hasProducts())
        <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#products-{{ $categoryArr['category']->id }}" role="button" aria-expanded="false" aria-controls="collapseExample">
            View Products
        </a>
        @endif
    </span>

    <div class="collapse mt-3" id="products-{{ $categoryArr['category']->id }}">
        <div class="card card-body alert-info">
            <ul>
                @foreach ($categoryArr['category']->products as $product)
                    <li>{{ $product->title }}</li>
                @endforeach
            </ul>
        </div>
    </div>
</li>
@if (count($categoryArr['children']))
<li class="ml-3">
    <ul>
        @foreach ($categoryArr['children'] as $child)
            @include('categories.partials.tree-view', ['categoryArr' => $child])
        @endforeach
    </ul>
</li>
@endif